from __future__ import annotations

import base64
import io
from datetime import date

import matplotlib
matplotlib.use("Agg")  # headless rendering, safe for Colab/servers
import matplotlib.pyplot as plt
import pandas as pd


"""ASSISTED: Claude (claude-sonnet-4-6),
 Prompt: 'Implement Markdown report creation, a styled standalone HTML renderer, and a base64-embedded matplotlib price chart showing closing price, 
 SMA 50, SMA 200, and Bollinger Bands. Include a clear educational-use financial risk disclaimer.', 
 Date: 2026-09-02"""


RISK_DISCLAIMER = (
    "**Disclaimer:** This report is generated by an automated research "
    "assistant for educational and demonstration purposes only. It does "
    "not constitute financial advice, and no investment decision should "
    "be made solely on its basis. Past performance is not indicative of "
    "future results. Consult a licensed financial advisor before trading."
)


def _render_price_chart(df: pd.DataFrame, ticker: str) -> str:
    """Render a price + SMA + Bollinger Bands chart, return as base64 PNG string."""
    fig, ax = plt.subplots(figsize=(9, 4.5), dpi=130)
    tail = df.tail(180)  # last ~180 trading days for readability

    ax.plot(tail.index, tail["Close"], label="Close", color="#1f77b4", linewidth=1.4)
    ax.plot(tail.index, tail["SMA_50"], label="SMA 50", color="#ff7f0e", linewidth=1.0)
    ax.plot(tail.index, tail["SMA_200"], label="SMA 200", color="#2ca02c", linewidth=1.0)
    ax.fill_between(
        tail.index, tail["bb_lower"], tail["bb_upper"], color="#1f77b4", alpha=0.08, label="Bollinger Band"
    )
    ax.set_title(f"{ticker} - Price, Moving Averages & Bollinger Bands (last 180 sessions)")
    ax.set_ylabel("Price (USD)")
    ax.legend(loc="upper left", fontsize=8)
    ax.grid(alpha=0.25)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def build_markdown_report(
    summary: dict,
    sentiment_results: list,
    aggregate_sentiment: float,
    trade_signal,
) -> str:
    """Build the one-page Markdown brief."""
    top_headlines = sentiment_results[:3]
    headline_lines = "\n".join(
        f"- **[{h.sentiment.upper()}]** ({h.confidence:.2f} conf.) {h.headline} — _{h.brief_reason}_"
        for h in top_headlines
    ) or "- No headlines available."

    signal_block = (
        f"**Signal: {trade_signal.signal}**\n\n{trade_signal.justification}\n\n"
        f"Key factors: {', '.join(trade_signal.key_factors)}"
        if trade_signal is not None
        else "_Signal unavailable (LLM call failed)._"
    )

    md = f"""# {summary.get('company_name', summary['ticker'])} ({summary['ticker']}) — Equity Research Brief
_Generated {date.today().isoformat()} · as of {summary['as_of_date']}_

## Company Snapshot
| Metric | Value |
|---|---|
| Current Price | ${summary['current_price']} |
| 52-Week High | ${summary['52_week_high']} |
| 52-Week Low | ${summary['52_week_low']} |
| Trailing P/E | {summary['trailing_pe']} |
| YTD Return | {summary['ytd_return_pct']}% |
| Momentum Signal | {summary['momentum_signal'].capitalize()} |

## Technical Outlook
| Indicator | Value |
|---|---|
| SMA 50 | {summary['indicators']['sma_50']} |
| SMA 200 | {summary['indicators']['sma_200']} |
| RSI (14) | {summary['indicators']['rsi_14']} |
| MACD Line | {summary['indicators']['macd_line']} |
| MACD Signal | {summary['indicators']['macd_signal']} |
| MACD Histogram | {summary['indicators']['macd_hist']} |
| Bollinger Upper | {summary['indicators']['bb_upper']} |
| Bollinger Lower | {summary['indicators']['bb_lower']} |

## News Sentiment Summary
Aggregate sentiment score: **{aggregate_sentiment:+.3f}** (range -1.0 to +1.0), based on {len(sentiment_results)} classified headlines.

Top headlines:
{headline_lines}

## LLM Recommendation
{signal_block}

## Risk Disclaimer
{RISK_DISCLAIMER}
"""
    return md


def render_html_report(markdown_text: str, df: pd.DataFrame, ticker: str, output_path: str) -> str:
    """Render the markdown report as a styled, self-contained HTML page with an embedded chart."""
    try:
        import markdown as md_lib
        body_html = md_lib.markdown(markdown_text, extensions=["tables"])
    except ImportError:
        # Minimal fallback if the `markdown` package isn't installed: wrap as <pre>
        body_html = f"<pre>{markdown_text}</pre>"

    chart_b64 = _render_price_chart(df, ticker)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{ticker} Equity Research Brief</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 820px;
          margin: 40px auto; padding: 0 20px; color: #1a1a1a; line-height: 1.55; }}
  h1 {{ font-size: 1.6rem; border-bottom: 2px solid #1f77b4; padding-bottom: 8px; }}
  h2 {{ font-size: 1.15rem; color: #1f77b4; margin-top: 28px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 10px 0; }}
  th, td {{ border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 0.92rem; }}
  th {{ background: #f4f7fb; }}
  img {{ max-width: 100%; border: 1px solid #eee; border-radius: 6px; margin: 12px 0; }}
  .disclaimer {{ background: #fff8e1; border-left: 4px solid #f0ad4e; padding: 10px 16px;
                 font-size: 0.85rem; margin-top: 24px; }}
</style>
</head>
<body>
{body_html}
<img src="data:image/png;base64,{chart_b64}" alt="{ticker} price chart">
</body>
</html>"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)
    return output_path
